
services:
  postgres:
    image: postgres:15
    container_name: jira-postgres
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jira -d jiradb"]
      interval: 10s
      timeout: 5s
      retries: 10

  jira:
    image: atlassian/jira-software:latest   # pin a tag like 10.x.x if you want
    container_name: jira
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      JVM_MINIMUM_MEMORY: 1g
      JVM_MAXIMUM_MEMORY: 2g
      ATL_JDBC_URL: "jdbc:postgresql://postgres:5432/jiradb"
      ATL_JDBC_USER: "jira"
      ATL_JDBC_PASSWORD: "jira"
      ATL_DB_TYPE: "postgres72"
      TZ: "Asia/Kolkata"
    volumes:
      - jiradata:/var/atl

volumes:
  dbdata:
  jiradata:
